// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkbgfzinvevclncsfoha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrYmdmemludmV2Y2xuY3Nmb2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODg5ODgsImV4cCI6MjA2NDE2NDk4OH0.pdPxJuDrqiR9QvO5tTOCfb_Z40VvlNGEdIsYdosUPeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);