// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktygzkbdizdqtsarhkrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eWd6a2JkaXpkcXRzYXJoa3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODg5MjcsImV4cCI6MjA2NDI2NDkyN30.o-eeUyCazlmPiwp2tI4v_F0lMOhv_EUA8jjWj06qyj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);